sudo: required
services:
    - docker
dist: trusty
language: python
python:
    - 3.5
    - 3.6
env:
    global:
        - THEANO_FLAGS='floatX=float32'
    matrix:
        - KERAS_BACKEND=tensorflow
before_install:
    - pip install -U pip
    - travis_wait travis_retry pip install -r requirements-tests.txt
    - travis_wait travis_retry pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - travis_wait travis_retry pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then travis_wait travis_retry pip install "black==19.10b0"; fi
    - python -c 'import tensorflow; print(tensorflow.__version__)'
    - python -c 'import theano; print(theano.__version__)'
    - python -c 'import lasagne; print(lasagne.__version__)'
    - python -c 'import torch; print(torch.__version__)'
    - python -c 'import keras; print(keras.__version__)'
    - python -c 'import mxnet; print(mxnet.__version__)'
    - python -c 'import jaxlib; print(jaxlib.__version__)'
    - python -c 'import jax; print(jax.__version__)'
install:
    - pip install -e .
script:
    - flake8
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --verbose .; fi
    - pytest --collect-only
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --verbose
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --cov-append --verbose --backend pytorch
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --cov-append --verbose --backend jax
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --cov-append --verbose --backend theano
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --cov-append --verbose --backend mxnet
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --cov-append --verbose --backend keras
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --cov-append --verbose --backend tensorflow-eager
    - pytest --pdb --cov-report term-missing --cov=foolbox --doctest-modules --cov-append --verbose --backend tensorflow-graph
after_success:
    - coveralls
cache:
    - pip
    - apt
