name: Guide

on:
  push:
    branches:
      - master

jobs:
  vuepress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install vuepress1
      continue-on-error: true
      run: |
        apt update && apt install yarn
        yarn global add vuepress
    - name: Install vuepress2
      continue-on-error: true
      run: |
        npm install -g vuepress
    - name: Install vuepress3
      continue-on-error: true
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update && sudo apt install yarn
        sudo yarn global add vuepress
    - name: Build
      run: |
        cd guide && vuepress build
    - name: Push
      run: |
        cd guide/.vuepress/dist/ && git init && git add -A && git commit -m 'deploy'
        cd guide/.vuepress/dist/ && git push -f git@github.com:bethgelab/foolbox.git master:gh-pages
