name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1
      with:
        path: ~/.torch
        key: ${{ runner.os }}-torch
    - uses: actions/cache@v1
      with:
        path: ~/.keras
        key: ${{ runner.os }}-keras
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements-dev.txt
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements-dev.txt
    - name: flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: black
      run: |
        black --check --verbose .
    - name: Install package
      run: |
        pip install -e .
    - name: Install requirements.txt
      run: |
        pip install -r requirements.txt
    - name: mypy (package)
      run: |
        mypy -p foolbox
    - name: mypy (tests)
      run: |
        mypy tests/
    - name: Test with pytest
      run: |
        pytest --skipslow --cov-report term-missing --cov=foolbox --verbose --ignore tests/attacks/
    - name: Test with pytest (NumPy)
      run: |
        pytest --skipslow --cov-report term-missing --cov=foolbox --cov-append --verbose --backend numpy --ignore tests/attacks/
    - name: Test with pytest (PyTorch)
      run: |
        pytest --skipslow --cov-report term-missing --cov=foolbox --cov-append --verbose --backend pytorch --ignore tests/attacks/
    - name: Test with pytest (JAX)
      run: |
        pytest --skipslow --cov-report term-missing --cov=foolbox --cov-append --verbose --backend jax --ignore tests/attacks/
    - name: Test with pytest (TensorFlow)
      run: |
        pytest --skipslow --cov-report term-missing --cov=foolbox --cov-append --verbose --backend tensorflow --ignore tests/attacks/
    - name: Codecov
      continue-on-error: true
      env:
          CODECOV_TOKEN: "7ca7a1ce-a549-4dce-943a-d66e9ef60b12"
      run: |
        codecov
    - name: Coveralls
      continue-on-error: true
      env:
        COVERALLS_REPO_TOKEN: "mXzVxVyQFEpb5TeaDW79LhHrhSL12pJVu"
      run: |
        coveralls
